export const scenes = {
  scenes: [
    {
      key: 0,
      name: 'main-world',
      genericSky: 'assets/skybox/default_enviroment.jpg',
      PosYCamMap: 100,
      loadScene: {
        url: 'assets/enviroments/orchard_road/',
        fileName: 'ixcity.gltf',
      },
      colliders: 'Colliders',
      teleports: [
        {
          name: 'Lucky_Plaza',
          size: {
            height: 1,
            width: 1.5,
          },
          position: { x: 76.5523, y: 0, z: 30.3181 },
          linkto: 'Showroom_Web',
          rotate: 0,
        },
        {
          name: 'Ngee_And_City',
          size: {
            height: 1,
            width: 4,
          },
          position: { x: -37.3318, y: 0, z: -21.8178 },
          linkto: 'Showroom_Web',
          rotate: 270,
        },
        {
          name: 'TANG',
          size: {
            height: 1,
            width: 3,
          },
          position: { x: -98.5439, y: 0, z: 25.0821 },
          linkto: 'Shoes_Shop',
          rotate: 180,
        },
        {
          name: 'ASEAN',
          size: {
            height: 1,
            width: 2,
          },
          position: { x: -187.602, y: 0, z: 15.2849 },
          linkto: 'Shoes_Shop',
          rotate: 90,
        },
      ],
      npc: [
        {
          key: 0,
          posCurrent: { x: -50, y: 0, z: 70 },
          rotCurrent: { x: 0, y: 90, z: 0 },
          url: 'assets/avatar/',
          file: 'animation-man.glb',
          scalNpc: 1,
          moveStyle: {
            timePerFrame: 30,
            loop: 'cycle',
            frames: [
              { distance: 50, name: 'move' },
              { time: 1, rotateY: 180, name: 'rotation' },
              { distance: 50, name: 'move' },
              { time: 1, rotateY: 180, name: 'rotation' },
            ],
          },
        },
        {
          key: 1,
          posCurrent: { x: 5, y: 0, z: 75 },
          rotCurrent: { x: 0, y: 90, z: 0 },
          url: 'assets/avatar/',
          file: 'animation-man.glb',
          scalNpc: 1,
          moveStyle: {
            timePerFrame: 30,
            loop: 'cycle',
            frames: [
              { distance: 50, name: 'move' },
              { time: 1, rotateY: 90, name: 'rotation' },
              { distance: 5, name: 'move' },
              { time: 1, rotateY: 90, name: 'rotation' },
              { distance: 50, name: 'move' },
              { time: 1, rotateY: 90, name: 'rotation' },
              { distance: 5, name: 'move' },
            ],
          },
        },
        {
          key: 2,
          posCurrent: { x: 40, y: 0, z: 65 },
          rotCurrent: { x: 0, y: 90, z: 0 },
          url: 'assets/avatar/',
          file: 'woman-catwalk.glb',
          scalNpc: 1,
        },
      ],
    },
    {
      key: 1,
      name: 'Showroom_Web',
      genericSky: 'assets/skybox/default_enviroment.jpg',
      PosYCamMap: 6,
      loadScene: {
        url: 'assets/interiors/ShowRoom/',
        fileName: 'Showroom_Web.gltf',
      },
      colliders: 'Collider',
      teleports: [
        {
          name: 'panel_home',
          size: {
            height: 1,
            width: 1.5,
          },
          position: { x: -2.2552, y: 0, z: -0.365324 },
          linkto: 'main-world',
          rotate: 0,
        },
      ],
      npc: [
        {
          key: 0,
          posCurrent: { x: 3.5, y: 0, z: 2.5 },
          rotCurrent: { x: 0, y: 45, z: 0 },
          url: 'assets/npcs/npc1/',
          file: 'npc1.gltf',
          scalNpc: 1,
          // moveStyle: {
          //   timePerFrame: 30,
          //   loop: 'cycle',
          //   frames: [
          //     { distance: 50, name: 'move' },
          //     { time: 1, rotateY: Math.PI, name: 'rotation' },
          //     { distance: 50, name: 'move' },
          //     { time: 1, rotateY: Math.PI, name: 'rotation' },
          //   ],
          // },
        },
        {
          key: 1,
          posCurrent: { x: 5, y: 0, z: -3 },
          rotCurrent: { x: 0, y: 100, z: 0 },
          url: 'assets/npcs/npc2/',
          file: 'npc2.gltf',
          scalNpc: 1,
        },
      ],
      products: [
        // {
        //   id: 0,
        //   name: 'Bag 00',
        //   position: { x: 4.7553, y: 2.12535, z: 1.41063 },
        //   rotation: { x: 0, y: 0, z: 0 },
        //   url: 'assets/products/bag1_1/',
        //   fileName: 'bag_open.gltf',
        //   changeStatus: {
        //     url: 'assets/Interior/ShowRoom/',
        //     fileName: 'Bag_01_Closed.gltf',
        //   },
        //   price: 20,
        //   color: ['dark', 'yellow', 'blue'],
        //   size: ['XS', 'S', 'M', 'L', 'XL'],
        //   description: 'grey, cotton',
        //   thumbnail: 'assets/products/bag1/thumbnail.jpg',
        // },
        {
          id: 1,
          name: 'Bag 01',
          position: { x: 4.79747, y: 2.21493, z: 1.51877 },
          rotation: { x: 0, y: -25.2562, z: 0 },
          url: 'assets/products/bag1/',
          fileName: 'Bag_01_Closed.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/bag1/thumbnail.jpg',
        },
        {
          id: 2,
          name: 'Bag 02',
          position: { x: 4.70508, y: 0.986653, z: 1.59027 },
          rotation: { x: 0, y: -39.2324, z: 0 },
          url: 'assets/products/bag2/',
          fileName: 'bag_02.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/bag2/thumbnail.jpg',
        },
        {
          id: 3,
          name: 'Bag 03',
          position: { x: 5.1973, y: 2.24454, z: 0.532696 },
          rotation: { x: 0, y: -10.8233, z: 0 },
          url: 'assets/products/bag3/',
          fileName: 'bag_03.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/bag3/thumbnail.jpg',
        },
        {
          id: 4,
          name: 'Shoes 01',
          position: { x: 5.33865, y: 0.960404, z: -2.11451 },
          rotation: { x: 0, y: 0, z: 0 },
          url: 'assets/products/shoes1/',
          fileName: 'shoes_01.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shoes1/thumbnail.jpg',
        },
        {
          id: 5,
          name: 'Shoes 02',
          position: { x: 5.3826, y: 0.946647, z: -0.942498 },
          rotation: { x: 0, y: 0, z: 0 },
          url: 'assets/products/shoes2/',
          fileName: 'shoes_02.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shoes2/thumbnail.jpg',
        },
        {
          id: 6,
          name: 'Shoes 03',
          position: { x: 5.29357, y: 1.57511, z: 0.113774 },
          rotation: { x: 0, y: 0, z: 0 },
          url: 'assets/products/shoes3/',
          fileName: 'shoes_03.gltf',
          price: 200,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shoes3/thumbnail.jpg',
        },
        {
          id: 7,
          name: 'Shirt 01',
          position: { x: 0.132221, y: 2, z: -5.90219 },
          rotation: { x: 0, y: 69.6883, z: 0 },
          url: 'assets/products/shirt1/',
          fileName: 'shirt_01.gltf',
          price: 2025,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shirt1/thumbnail.jpg',
        },
        {
          id: 8,
          name: 'Shirt 02',
          position: { x: -1.4779, y: 2, z: -5.32468 },
          rotation: { x: 0, y: 77.9193, z: 0 },
          url: 'assets/products/shirt2/',
          fileName: 'shirt_02.gltf',
          price: 100,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shirt2/thumbnail.jpg',
        },
        {
          id: 9,
          name: 'Dress 01',
          position: { x: 0.431713, y: 2, z: 3.25897 },
          rotation: { x: 0, y: -167.845, z: 0 },
          url: 'assets/products/dress1/',
          fileName: 'dress_01.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/dress1/thumbnail.jpg',
        },
        {
          id: 10,
          name: 'Dress 02',
          position: { x: -2.21558, y: 2, z: 1.94919 },
          rotation: { x: 0, y: 158.775, z: 0 },
          url: 'assets/products/dress2/',
          fileName: 'dress_02.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/dress2/thumbnail.jpg',
        },
        {
          id: 11,
          name: 'Dress 03',
          position: { x: 3.5, y: 2, z: 3.19435 },
          rotation: { x: 0, y: 210, z: 0 },
          url: 'assets/products/dress3/',
          fileName: 'dress3.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/dress3/thumbnail.jpg',
        },
        {
          id: 12,
          name: 'Shirt 03',
          position: { x: -3, y: 2, z: -4.35545 },
          rotation: { x: 0, y: 77.9193, z: 0 },
          url: 'assets/products/shirt3/',
          fileName: 'shirt3.gltf',
          price: 20,
          colors: ['dark', 'yellow', 'blue'],
          sizes: ['XS', 'S', 'M', 'L', 'XL'],
          description: 'grey, cotton',
          thumbnail: 'assets/products/shirt3/thumbnail.jpg',
        },
      ],
    },
    {
      key: 2,
      name: 'Clothes_Shop',
      genericSky: 'assets/skybox/default_enviroment.jpg',
      PosYCamMap: 6,
      loadScene: {
        url: 'assets/interiors/shop2/',
        fileName: 'secondInterior.gltf',
      },
      colliders: 'Collider',
      teleports: [
        {
          name: 'panel_home',
          size: {
            height: 1,
            width: 1.5,
          },
          position: { x: 0, y: 0, z: 9.02426 },
          linkto: 'main-world',
          rotate: 0,
        },
      ],
    },
    {
      key: 3,
      name: 'Shoes_Shop',
      genericSky: 'assets/skybox/default_enviroment.jpg',
      PosYCamMap: 6,
      loadScene: {
        url: 'assets/interiors/shop1/',
        fileName: 'firstInterior.gltf',
      },
      colliders: 'Collider',
      teleports: [
        {
          name: 'panel_home',
          size: {
            height: 1,
            width: 1.5,
          },
          position: { x: 0, y: 0, z: 13.7831 },
          linkto: 'main-world',
          rotate: 0,
        },
      ],
    },
  ],
  avatars: [
    {
      id: 1,
      location: 'assets/avatar/hana/full/',
      value: 'hana.gltf',
    },
    {
      id: 2,
      location: 'assets/avatar/olivia/',
      value: 'olivia.gltf',
    },
    {
      id: 3,
      location: 'assets/avatar/steven/',
      value: 'steven.gltf',
    },
  ],
};